vendor_id: 0x00004321
product_id: 0x0000100a

assign_activate: 0x0000       # DC sync
auto_fault_reset: true       # Manual fault reset

# sdo:  # sdo data to be transferred at drive startup
  # - {index: 0x60C2, sub_index: 1, type: int8, value: 10} # Set interpolation time for cyclic modes to 10 ms
  # - {index: 0x60C2, sub_index: 2, type: int8, value: -3} # Set base 10-3s
  # - {index: 0x60b0, sub_index: 0, type: uint16, value: 1631}  # Fault reset
  # - {index: 0x607c, sub_index: 0, type: uint16, value: 1631}  # Fault reset
  # - {index: 0x6040, sub_index: 0, type: uint16, value: 0x80}  # Fault reset
  # - {index: 0x6040, sub_index: 0, type: uint16, value: 0x0006} # Shut down
  # - {index: 0x6040, sub_index: 0, type: uint16, value: 0x0007} # Switch on
  # - {index: 0x6040, sub_index: 0, type: uint16, value: 0x000F} # Enable operation

  # - {index: 0x6065, sub_index: 0, type: uint32, value: 1000000}
  # - {index: 0x6040, sub_index: 0, type: uint16, default: 0}	# Control word

rpdo:
  - index: 0x1600
    channels:
      - {index: 0x6040, sub-index: 0, type: uint16, default: 0} # Control Word
      - {index: 0x607a, sub-index: 0, type: int32, command_interface: position, default: .nan, offset: 0} # Target Position
      - {index: 0x60b8, sub-index: 0, type: uint16, default: 0}
      

tpdo:  # TxPDO 
  - index: 0x1a00
    channels:
      - {index: 0x603f, sub_index: 0, type: uint16}
      - {index: 0x6041, sub_index: 0, type: uint16}
      - {index: 0x6061, sub_index: 0, type: uint8}
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, offset: 0}
      - {index: 0x60b9, sub_index: 0, type: uint16}
      - {index: 0x60ba, sub_index: 0, type: uint32}
      - {index: 0x60fd, sub_index: 0, type: uint32}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}